### ISSUE TITLE
Missing return warnings for GCC for switch statements 

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-elements#1255] opened 2019-04-08 19:59 UTC
Several switch statements do not provide a trailing return or default case statement, leading GCC to spew complaints about missing return statements in memOp.h, nicEvents.h, and shmemapi.h

**Comment by hughes-c** [comment] 2019-07-16 07:17
@jjwilke Should this go into 9.1?

**Comment by jwilso** [comment] 2019-10-21 22:05
@jjwilke @hughes-c Was this ever addressed? I will leave it open if so.

**Comment by hughes-c** [comment] 2019-10-22 20:01
@jwilso Not that I'm aware of.

**Comment by nmhamster** [comment] 2021-02-19 01:20
@allevin / @jjwilke - do we have a list of these we can knock out for the release?

**Comment by allevin** [comment] 2021-02-19 15:19
@jjwilke do you know what version of the gcc compiler was throwing the complaints?   
I will try to do a warnings scrub next week.

**Comment by allevin** [comment] 2021-04-07 13:12
@jjwilke @nmhamster I cannot reproduce these build warnings.  I tried GCC 4.8 and GCC 6.1... The issue was submitted in 2019, and may have been cleaned up since.  I recommend closing.

**Closed** 2023-07-03 21:12 UTC
