### ISSUE TITLE
Vanadis Segfault

### ISSUE THREAD

**Issue by Connie120** [sstsimulator/sst-elements#1925] opened 2022-07-15 19:49 UTC
Hello! I downloaded the latest sst elements and sst core from the master branch and tried to run the hello-world example in the tests/basic-io/hello-world/riscv64/ folder. But I encountered this segfault, and here's the backtrace info. 

![Screenshot from 2022-07-15 15-43-10](https://user-images.githubusercontent.com/54909364/179299672-c594cc49-859a-4aac-a694-b7c040dd56d0.png)

The command I used to run is "sst tests/basic_vanadis.py" and I've changed "MIPS" to "RISCV64". The operating system I'm using is Ubuntu 20.04. Any help would be appreciated, thank you!

**Comment by jpkenny** [comment] 2022-07-18 16:06
Hi,
This is likely a duplicate of issue #1920. There is a known bug in Vanadis and work on a fix is underway.

**Comment by nmhamster** [comment] 2022-10-28 12:39
Will close this issue, please re-open if this problem re-occurs.

**Closed by nmhamster** 2022-10-28 12:39 UTC
Labels: Bug, SST-Vanadis
